apiVersion: cluster.lostar.com/v1
kind: Rediscluster
metadata:
  name: redis-1
  labels:
    app: redis-app
    tire: backend
    operator: "true"
spec:
  name: redis-1
  replicas: 1
  image: public.ecr.aws/ubuntu/redis:latest
  env:
  - name: REDIS_PASSWORD
    value: "fs93foqoe01"