# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cluster.lostar.com_redisclusters.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_redisclusters.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_redisclusters.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

patches:
- target:
    kind: CustomResourceDefinition
    name: redisclusters.cluster.lostar.com
  patch: |-
    - op: add
      path: /spec/versions/0/additionalPrinterColumns
      value: 
        - name: Status
          type: string
          description: "The status of the custom resource"
          jsonPath: .status.phase
        - name: Age
          type: date
          description: "Time since resource creation"
          jsonPath: .metadata.creationTimestamp


# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
